#!/bin/bash
# Script to generate data for `four_terrain` sample

# exit after firts error
set -e

# if conda available activate earthren environment
if command -v conda >/dev/null 2>&1; then
	# Source the Conda initialization script
	source "$(conda info --base)/etc/profile.d/conda.sh"
	conda activate earthren
	echo "earthren environment activated"
fi

echo "--> generate elevation tiles"
python3 split_half.py ../data/plzen_elev.tif

echo "--> generate satellite tiles"
python3 split_half.py ../data/plzen_rgb.tif

echo "--> install"
TARGET_PATH="../data/gen/four_terrain"
mkdir -p $TARGET_PATH
mv ./out/plzen_*.tif $TARGET_PATH
echo "installed to $TARGET_PATH"

echo "--> clean"
rm -r ./out

echo "done!"
