#!/bin/bash
# Script to generate data for `grid_more_details` sample.

# exit after first error
set -e

# - we want plzen tile to represent level 0 tile
# - then we want to split level 0 tile into 4 tiles to generate level 1 tiles
# - then we want to split each level 1 tile into 4 tiles to generate level 2 tiles (16 tiles)
# - (optional) we want to scale level 0 tile to 25% (we do not need that much details there)
# - (optional) we want to scale level 1 tils to 50% (we want only level 2 be in a full detail)
TARGET_PATH="../data/gen/lod_tiles"

# if conda available activate earthren environment
if command -v conda >/dev/null 2>&1; then
	# Source the Conda initialization script
	source "$(conda info --base)/etc/profile.d/conda.sh"
	conda activate earthren
	echo "earthren environment activated"
fi

rm -rf out
mkdir out

echo "--> generate elevation tiles"

# generate level 0 tile
echo "- level 0"
mkdir out/level0
cp ../data/plzen_elev.tif out/level0

# generate level 1 tiles
echo "- level 1"
python3 split_tile_overlap.py --row-tiles 2 ../data/plzen_elev.tif

# take level 1 elevation tiles and save them for later deployment
mkdir out/level1
mv out/plzen_elev_*.tif out/level1

# generate level 2 tiles
echo "- level 2"
mkdir out/level2

for tile in out/level1/plzen_elev_*.tif; do
	# split tile
	python3 split_tile_overlap.py --row-tiles 2 "$tile"
	
	# there we need to modify file names before move tiles
	for new_tile in out/plzen_elev_*.tif; do
		python3 rename_tile.py "$new_tile"
	done

	# move tiles to level2 folder
	mv out/plzen_elev_*.tif out/level2
done

# echo "--> generate satellite tiles"

# # generate level 2 satellite tiles
# python3 split_tile.py --row-tiles $GRID_SIZE ../data/plzen_rgb.tif

# # take level 2 satelite tiles and save tham into level2 directory
# cd out
# mv plzen_rgb_*.tif level2
# cd ..

# cp out/level2/plzen_rgb_0_0.tif out/plzen_rgb.tif

# # generate level 3 satellite tiles
# python3 split_tile.py --row-tiles $GRID_SIZE out/plzen_rgb.tif

# # take level 3 elevation tiles and save tham for later use
# cd out
# mv plzen_rgb_*.tif level3
# cd ..


# echo "--> install"
# mkdir -p $TARGET_PATH
# mv ./out/level* $TARGET_PATH
# echo "installed to $TARGET_PATH"


# echo "--> dataset description"
# python3 create_dataset_desc.py $TARGET_PATH/level2 $GRID_SIZE
# python3 create_dataset_desc.py $TARGET_PATH/level3 $GRID_SIZE


# echo "--> clean"
# rm -r ./out

# echo "check result with"
# echo "  ls $TARGET_PATH"
# echo "command"

echo "done!"
