#!/bin/bash
# Prepares elevation and satellite tiles for Plzen area

# exit after firts error
set -e

DATA_PATH=$(pwd)/../data

echo "data-directory=$DATA_PATH"

echo "-> elevation"

cd ~/gis/data/srtm

echo "-> project into UTM"

gdalwarp -t_srs EPSG:32633 n49_e013_1arc_v3.tif n49_e013_1arc_v3_utm.tif

echo "-> crop Plzen area"
gdal_translate -projwin 372369.741, 5521901.825, 409692.244, 5484579.322 n49_e013_1arc_v3_utm.tif plzen_elev.tif

mv plzen_elev.tif "$DATA_PATH"

echo "-> clean"
rm n49_e013_1arc_v3_utm.tif

echo "-> satellite"
cd ~/gis/data/landsat8/LC08_L1TP_192025_20240513_20240520_02_T1

echo "-> merge b4 b3 and b2 bands together"
gdal_merge.py -separate -o output_rgb.tif LC08_L1TP_192025_20240513_20240520_02_T1_B4.TIF LC08_L1TP_192025_20240513_20240520_02_T1_B3.TIF LC08_L1TP_192025_20240513_20240520_02_T1_B2.TIF

echo "-> crop Plzen area"
gdal_translate -projwin 372369.741, 5521901.825, 409692.244, 5484579.322 output_rgb.tif plzen_rgb16.tif

echo "-> histogram stretch"
gdal_contrast_stretch -percentile-range 0.02 0.98 plzen_rgb16.tif plzen_rgb.tif

mv plzen_rgb.tif "$DATA_PATH"

echo "-> clean"
rm output_rgb.tif plzen_rgb16.tif

echo "plzen_rgb.tif plzen_elev.tif created in $DATA_PATH"

echo "done!"
